### ISSUE TITLE
Modifying DNS servers using original MFDeploy results in incorrect behaviour when DHCP is enabled

### ISSUE THREAD

**Issue by NameOfTheDragon** [netduino/Netduino.IP#1]
Please refer to this thread: http://forums.netduino.com/index.php?/topic/12008-netduinoip-dns-resolution/

It seems that the non-IPv6 version of `MFDeploy` is not correctly setting the "get DNS servers via DHCP" flag in the `ER_CONFIG` sector when you enter all-zeros for the DNS servers.

This results in the network being incorrectly configured with no DNS servers and an attempt to read the DNS server addresses throws `NullReferenceException`, and Netduino is unable to resolve any host names, even though the DNS servers have been provided and correctly received in the DHCP Offer.

CW suggested that a workaround might be possible in a future firmware version.

Here is the code I am using to read the DNS servers (`Dbg.Trace` can be replaced with `Debug.Print`):  

```
    static void WaitForValidIpAddress()
        {
        NetworkInterface[] networkInterfaces;
        Dbg.Trace("Waiting for valid IP address", Source.NetworkServer);
        do
            {
            Thread.Sleep(100);
            networkInterfaces = NetworkInterface.GetAllNetworkInterfaces();
            } while (networkInterfaces[0].IPAddress == "0.0.0.0");

        Dbg.Trace("Found " + networkInterfaces.Length + " network interfaces - details as follows...", Source.NetworkServer);
        for (int i = 0; i < networkInterfaces.Length; i++)
            {
            var nic = networkInterfaces[i];
            Dbg.Trace("Network interface: " + i, Source.NetworkServer);
            Dbg.Trace("  Interface type: " + nic.NetworkInterfaceType, Source.NetworkServer);
            Dbg.Trace("  IPv4 address: " + nic.IPAddress, Source.NetworkServer);
            Dbg.Trace("  Default gateway: " + nic.GatewayAddress, Source.NetworkServer);
            Dbg.Trace("  Subnet mask: " + nic.SubnetMask, Source.NetworkServer);

            var dnsServers = nic.DnsAddresses;
            Dbg.Trace("  DNS servers:", Source.NetworkServer);
            foreach (var dnsServer in dnsServers)
                {
                Dbg.Trace("    " + dnsServer, Source.NetworkServer);
                }
            }
        }
```

**Comment by NameOfTheDragon** [comment]
After further investigation, I tried using the new `MFDeploy` tool with IPv6 settings. Even using that tool, and even if the DNS servers are first programmed with valid static values, enabling DHCP results in a `NullReferenceException` when reading the DNS servers, and an inability to resolve host names.

**Comment by netduino** [comment]
Thank you for all of your tests, NameOfTheDragon.

Netduino.IP was relying on the "DHCP-specified DNS servers" flag, which is not necessarily set correctly from MFDeploy.  For backwards compatibility, we will now treat an empty set of DNS server entries (all-zero) as an indication that DNS servers should be specified by DHCP (when DHCP-allocated IP config is enabled).

This is fixed for the Netduino.IP v1.0.1 release.

**Comment by NameOfTheDragon** [comment]
My testing suggests that this isn't fixed (sorry). When I configure my Netduino Plus 2 for DHCP, I get a `NullReferenceException` when I try to read the `nic.DnsServers` property. Note: it is not returning null, any attempt to just read the property throws the `NullReferenceException`. Whatever way you look at it, it has got to be a bug for a property getter to throw a `NullReferenceException` no matter what state the network is in.

In my test code, which is based on your 'network time' sample, I have ensured that the link layer is active and that the NIC has a valid IP address (which also comes from DHCP, so DHCP itself must be working).

I have configured my Netduino with your 'special' version of MFDeploy that has the IPv6 settings pane. I have configured to obtain both the IP address and the DNS servers automatically. Attached is a screen shot of my settings.
![n2plusdhcpconfig](https://github-cloud.s3.amazonaws.com/assets/1268490/10565315/8a8ad822-75c5-11e5-92c4-a72adc5608b0.PNG)

**Comment by NameOfTheDragon** [comment]
As a workaround, the DNS servers can be set to 0.0.0.0 in MFDeploy and then the network stack does work as expected - however the DnsAddresses property then returns an empty array, rather than the actual DNS servers being used. When I run my test code, I see the following output that shows DNS is actually working and has picked up the servers from DHCP:

<pre>
[Network     ] Link layer available
[Network     ] Waiting for network layer
[Network     ] Network address changed:
[Network     ] 5C:86:4A:00:87:2C 192.168.16.7 (DHCP)
[Network     ] Found 1 network interfaces - details as follows...
[Network     ] Network interface: 0
[Network     ]   Interface type: 6
[Network     ]   IPv4 address: 192.168.16.7
[Network     ]   Default gateway: 192.168.16.1
[Network     ]   Subnet mask: 255.255.255.0
[Network     ]   No DNS servers - empty list returned
[Network Time] Attempting to set the time from pool.ntp.org
[Network Time] Resolved IP Address: 85.119.80.232
[Network Time] Network time received
[Network Time] UTC Time: 10/18/2015 17:44:26
[Unspecified ] Set system time to: 10/18/2015 17:44:26 UTC
[Unspecified ] Clock set to 10/18/2015 17:44:26
</pre>

However, this is not what I would call "correct behaviour" since configuring the Netduino to use "automatic settings" simply doesn't work.
